pkg/objects/Employee__c.object
<CustomObject>
    <description>Objeto responsável por gerenciar funcionários.</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pkg/objects/SimilarEmployeeProfile__c.object
<CustomObject>
    <description>Objeto responsável por gerenciar perfis semelhantes dos funcionários.</description>
    <fields>
        <fullName>SimilarEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relacionamento de pesquisa funcionário semelhante</description>
        <inlineHelpText>Funcionário similar</inlineHelpText>
        <label>Similar Employee</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Funcionário semelhante não pode ser o mesmo do funcionário de origem.</errorMessage>
            <filterItems>
                <field>Employee__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.SourceEmployee__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Similar Employee Profiles (Funcionário Semelhante)</relationshipLabel>
        <relationshipName>FuncionarioSemelhante</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SourceEmployee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relacionamento de pesquisa funcionário de origem.</description>
        <inlineHelpText>Funcionário de origem</inlineHelpText>
        <label>Source Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Similar Employee Profiles (Funcionário de Origem)</relationshipLabel>
        <relationshipName>FuncionarioOrigem</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Similar Employee Profile</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Similar Profile Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Similar Employee Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SimilarEmployeeTriggerHandlerTest.cls
@isTest
public class SimilarEmployeeTriggerHandlerTest {
    
    static testmethod void createSimilarEmployeeProfileTest() {
        
        Employee__c newEmployee1 = new Employee__c() ;
        newEmployee1.Name = 'Test1';
        insert newEmployee1;
        
        Employee__c newEmployee2 = new Employee__c() ;
        newEmployee2.Name = 'Test2';
        insert newEmployee2;
        
        try {
            
            SimilarEmployeeProfile__c newSimilarEmployeeProfile1 = new SimilarEmployeeProfile__c();
            newSimilarEmployeeProfile1.SourceEmployee__c = newEmployee1.Id;
            newSimilarEmployeeProfile1.SimilarEmployee__c = newEmployee2.Id;
            insert newSimilarEmployeeProfile1;
            
            SimilarEmployeeProfile__c newSimilarEmployeeProfile2 = new SimilarEmployeeProfile__c();
            newSimilarEmployeeProfile2.SourceEmployee__c = newEmployee1.Id;
            newSimilarEmployeeProfile2.SimilarEmployee__c = newEmployee2.Id;
            insert newSimilarEmployeeProfile2;
            
        }catch(Exception e) {
            
            system.debug(e.getMessage());
            Boolean expectExceptionThrown = e.getMessage().contains(System.Label.DuplicateRegistryError) ? true : false;
            system.assertEquals(expectExceptionThrown, true);
            
        }
        
    }
    
}