pkg/objects/SimilarEmployeeProfile__c.object
<CustomObject>
    <description>Objeto responsável por gerenciar perfis semelhantes dos funcionários.</description>
    <fields>
        <fullName>Function__c</fullName>
        <description>Lista de opção de funções do perfil semelhante.</description>
        <inlineHelpText>Função dos funcionários</inlineHelpText>
        <label>Function</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Funcao</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>SimilarEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relacionamento de pesquisa funcionário semelhante</description>
        <inlineHelpText>Funcionário similar</inlineHelpText>
        <label>Similar Employee</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Funcionário semelhante não pode ser o mesmo do funcionário de origem.</errorMessage>
            <filterItems>
                <field>Employee__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.SourceEmployee__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Similar Employee Profiles (Funcionário Semelhante)</relationshipLabel>
        <relationshipName>FuncionarioSemelhante</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SourceEmployee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relacionamento de pesquisa funcionário de origem.</description>
        <inlineHelpText>Funcionário de origem</inlineHelpText>
        <label>Source Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Similar Employee Profiles (Funcionário de Origem)</relationshipLabel>
        <relationshipName>FuncionarioOrigem</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Similar Employee Profile</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Similar Profile Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Similar Employee Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/globalValueSets/Funcao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Desenvolvedor</fullName>
    </customValue>
    <customValue>
        <fullName>Funcional</fullName>
    </customValue>
    <customValue>
        <fullName>Gerente</fullName>
    </customValue>
    <customValue>
        <fullName>Líder Técnico</fullName>
    </customValue>
    <customValue>
        <fullName>QA</fullName>
    </customValue>
    <customValue>
        <fullName>Scrum Master</fullName>
    </customValue>
    <customValue>
        <fullName>Tester</fullName>
    </customValue>
    <customValue>
        <fullName>UX Design</fullName>
    </customValue>
    <description>Lista de valor global para função.</description>
    <masterLabel>Funções</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SimilarEmployeeSelector.cls
public inherited sharing class SimilarEmployeeSelector {
    
    public static List<SimilarEmployeeProfile__c> getDuplicateListSimilarEmployeeProfile(SimilarEmployeeProfile__c similarEmployeeProfile) {

        return [SELECT Id,
                SimilarEmployee__c,
                SourceEmployee__c,
                Function__c
                FROM SimilarEmployeeProfile__c 
                WHERE ( SimilarEmployee__c =: similarEmployeeProfile.SimilarEmployee__c
                       AND SourceEmployee__c =: similarEmployeeProfile.SourceEmployee__c ) 
                OR ( SimilarEmployee__c =: similarEmployeeProfile.SourceEmployee__c 
                    AND SourceEmployee__c =: similarEmployeeProfile.SimilarEmployee__c )
        ];
    }
}