pkg/objects/SimilarEmployeeProfile__c.object
<CustomObject>
    <description>Objeto responsável por gerenciar perfis semelhantes dos funcionários.</description>
    <fields>
        <fullName>SimilarEmployee__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Relacionamento de pesquisa funcionário semelhante</description>
        <inlineHelpText>Funcionário similar</inlineHelpText>
        <label>Similar Employee</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Funcionário semelhante não pode ser o mesmo do funcionário de origem.</errorMessage>
            <filterItems>
                <field>Employee__c.Id</field>
                <operation>notEqual</operation>
                <valueField>$Source.SourceEmployee__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Similar Employee Profiles (Funcionário Semelhante)</relationshipLabel>
        <relationshipName>FuncionarioSemelhante</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SourceEmployee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Relacionamento de pesquisa funcionário de origem.</description>
        <inlineHelpText>Funcionário de origem</inlineHelpText>
        <label>Source Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Similar Employee Profiles (Funcionário de Origem)</relationshipLabel>
        <relationshipName>FuncionarioOrigem</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Similar Employee Profile</label>
    <nameField>
        <displayFormat>SE-{0000}</displayFormat>
        <label>Similar Profile Code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Similar Employee Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/SimilarEmployeeTriggerHelper.cls
public class SimilarEmployeeTriggerHelper {
     
    public static void validateDuplicateRecord(SimilarEmployeeProfile__c similarEmployeeProfile){

        List<SimilarEmployeeProfile__c> listSimilarEmployeeProfile = [
            SELECT Id
            FROM SimilarEmployeeProfile__c 
            WHERE ( SimilarEmployee__c =: similarEmployeeProfile.SimilarEmployee__c
            AND SourceEmployee__c =: similarEmployeeProfile.SourceEmployee__c ) 
            OR ( SimilarEmployee__c =: similarEmployeeProfile.SourceEmployee__c 
            AND SourceEmployee__c =: similarEmployeeProfile.SimilarEmployee__c )
        ];
        
        System.debug('listSimilarEmployeeProfile: ');
        System.debug(listSimilarEmployeeProfile);
        
        if (listSimilarEmployeeProfile.Size() > 0) {
            similarEmployeeProfile.addError('Não foi possivel salvar o registro.' + '\n' + 'Registro duplicado!');
        }
    }
    
}