force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Allocation code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pkg/objects/Alocation__c.object
<CustomObject>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date (or Expected End Date) of the Allocation</description>
        <inlineHelpText>End Date (or Expected End Date) of the Allocation</inlineHelpText>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberHoursDay__c</fullName>
        <description>The number of hours of the day that the Employee will be working in this Allocation.</description>
        <inlineHelpText>The number of hours of the day that the Employee will be working in this Allocation.</inlineHelpText>
        <label>Number of hours in the day</label>
        <precision>4</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Allocation Start Date</description>
        <inlineHelpText>Allocation Start Date</inlineHelpText>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Allocation code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pkg/objects/DailyAllocation__c.object
<CustomObject>
    <description>The daily record of Employee performance hours within an Allocation.</description>
    <fields>
        <fullName>Allocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allocation to which the daily allocation belongs.</description>
        <inlineHelpText>Allocation to which the daily allocation belongs.</inlineHelpText>
        <label>Allocation</label>
        <referenceTo>Alocation__c</referenceTo>
        <relationshipLabel>Daily Allocations</relationshipLabel>
        <relationshipName>Daily_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>To which day this Allocation refers.</description>
        <inlineHelpText>To which day this Allocation refers.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>NumberHoursDay__c</fullName>
        <description>Number of working hours per day.</description>
        <formula>Allocation__r.NumberHoursDay__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of working hours per day.</inlineHelpText>
        <label>Number of hours a day</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Daily Allocation</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Daily Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/CreateDailyAllocationService.cls
public class CreateDailyAllocationService {

    @InvocableMethod(label='createDailyAllocation')
    public static void createDailyAllocation (List<Alocation__c> allocations){
        
        List<DailyAllocation__c> dailyAllocation = new List<DailyAllocation__c>();
        
        for(Alocation__c all : allocations){
            DailyAllocation__c[] dailyAll = returnsAllocationCalendar(all);
            dailyAllocation.addAll(dailyAll);
        }
        
        if(dailyAllocation.size()>0) insert dailyAllocation;
    }
    
    public static List<DailyAllocation__c> returnsAllocationCalendar(Alocation__c allocation) 
    {
        List<DailyAllocation__c> dailyAllocation = new List<DailyAllocation__c>();
        DateTime startDate = DateTime.newInstance(allocation.StartDate__c, Time.newInstance(0, 0, 0, 0));
        DateTime endDate = DateTime.newInstance(allocation.EndDate__c, Time.newInstance(12, 0, 0, 0));
        
        // Holiday
        List<Holiday> holidaystb = CreateDailyAllocationSelector.returnsHolidays();
        List<date> holidays = new list<date>();
        for(holiday h : holidaystb)
            holidays.add(h.activitydate);        
        
        while (startDate <= endDate) {
            
            DailyAllocation__c dailyAll = new DailyAllocation__c();
            dailyAll.Allocation__c = allocation.Id;
            
            if (startDate.format('E') == 'Sat') startDate = startDate.addDays(2);
            else if (startDate.format('E') == 'Sun') startDate = startDate.addDays(1);
            
            dailyAll.Date__c = startDate.date();
            //dailyAll.NumberHoursDay__c = allocation.NumberHoursDay__c; //formula field
            
            if(startDate <= endDate) {
                if( ! holidays.contains(dailyAll.Date__c) )
                	dailyAllocation.add(dailyAll);
                else
                	{system.debug('Hollyday found');}
            }
            startDate = startDate.addDays(1);
        }
    	return dailyAllocation;
    }
}