force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Allocation code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pkg/objects/DailyAllocation__c.object
<CustomObject>
    <description>The daily record of Employee performance hours within an Allocation.</description>
    <fields>
        <fullName>Allocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allocation to which the daily allocation belongs.</description>
        <inlineHelpText>Allocation to which the daily allocation belongs.</inlineHelpText>
        <label>Allocation</label>
        <referenceTo>Alocation__c</referenceTo>
        <relationshipLabel>Daily Allocations</relationshipLabel>
        <relationshipName>Daily_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Daily Allocation</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Daily Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteDailyAllocationService.cls
public class DeleteDailyAllocationService {
    @InvocableMethod(label='deleteDailyAllocation')
    public static void DeleteDailyAllocation(List<Allocation__c> allocations)
    {
        Set<Id> ids= new Set<id>();
        for(Allocation__c allocation : allocations)
        	ids.add(allocation.id);
        
        DailyAllocation__c[] dailyAllocation = DeleteDailyAllocationSelector.returnsDailyAllocations(ids);
            
        if(dailyAllocation.size() > 0)
            delete dailyAllocation;  
    }
}