force-app/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status</description>
    <inlineHelpText>Status</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Inativa</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Allocation__c/Allocation__c.object-meta.xml
<CustomObject>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Allocation code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Allocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Allocation__c/fields/Employee__c.field-meta.xml
<CustomField>
    <fullName>Employee__c</fullName>
    <description>Identification of the Employee linked to this Allocation.</description>
    <inlineHelpText>Identification of the Employee linked to this Allocation.</inlineHelpText>
    <label>Professional</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Alocations (Funcionário)</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/Engagement__c.field-meta.xml
<CustomField>
    <fullName>Engagement__c</fullName>
    <description>Code used in Billing defines the cost/investment of a project.</description>
    <formula>Project__r.Engagement__c</formula>
    <inlineHelpText>Code used in Billing defines the cost/investment of a project.</inlineHelpText>
    <label>Engagement</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <description>Identification of the Project in which the Employee is allocated.</description>
    <inlineHelpText>Identification of the Project in which the Employee is allocated.</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Alocations</relationshipLabel>
    <relationshipName>Allocations</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Allocation__c/fields/ResponsibleManager__c.field-meta.xml
<CustomField>
    <fullName>ResponsibleManager__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Project Manager Code.</description>
    <inlineHelpText>Project Manager Code.</inlineHelpText>
    <label>Responsible Manager</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Alocations (Responsible Manager)</relationshipLabel>
    <relationshipName>Alocations</relationshipName>
    <type>Lookup</type>
</CustomField>

pkg/objects/Alocation__c.object
<CustomObject>
    <fields>
        <fullName>Employee__c</fullName>
        <description>Identification of the Employee linked to this Allocation.</description>
        <inlineHelpText>Identification of the Employee linked to this Allocation.</inlineHelpText>
        <label>Employee</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Alocations (Funcionário)</relationshipLabel>
        <relationshipName>Allocations</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>End Date (or Expected End Date) of the Allocation</description>
        <inlineHelpText>End Date (or Expected End Date) of the Allocation</inlineHelpText>
        <label>End date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Engagement__c</fullName>
        <formula>Project__r.Engagement__c</formula>
        <label>Engagement</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Identification of the Project in which the Employee is allocated.</description>
        <inlineHelpText>Identification of the Project in which the Employee is allocated.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>Alocations</relationshipLabel>
        <relationshipName>ProjectAllocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Allocation Start Date</description>
        <inlineHelpText>Allocation Start Date</inlineHelpText>
        <label>Start date</label>
        <type>Date</type>
    </fields>
    <label>Allocation</label>
    <nameField>
        <displayFormat>AL-{0000}</displayFormat>
        <label>Allocation code</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Alocations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

pkg/objects/DailyAllocation__c.object
<CustomObject>
    <description>The daily record of Employee performance hours within an Allocation.</description>
    <fields>
        <fullName>Allocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Allocation to which the daily allocation belongs.</description>
        <inlineHelpText>Allocation to which the daily allocation belongs.</inlineHelpText>
        <label>Allocation</label>
        <referenceTo>Alocation__c</referenceTo>
        <relationshipLabel>Daily Allocations</relationshipLabel>
        <relationshipName>Daily_Allocations</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <description>To which day this Allocation refers.</description>
        <inlineHelpText>To which day this Allocation refers.</inlineHelpText>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <label>Daily Allocation</label>
    <nameField>
        <displayFormat>AD-{0000}</displayFormat>
        <label>Daily Allocation</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Allocations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pkg/objects/Employee__c.object
<CustomObject>
    <description>Objeto responsável por gerenciar funcionários.</description>
    <fields>
        <fullName>Allocation__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Campo para registrar a alocação do funcionário.</description>
        <inlineHelpText>Alocação do funcionário.</inlineHelpText>
        <label>Allocation</label>
        <referenceTo>Alocation__c</referenceTo>
        <relationshipLabel>Employees</relationshipLabel>
        <relationshipName>Employees</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Campo para registrar o centro de custo dos funcionários.</description>
        <inlineHelpText>Centro de custo dos funcionários</inlineHelpText>
        <label>Cost Center</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>2000081</fullName>
                </value>
                <value>
                    <fullName>1008101</fullName>
                </value>
                <value>
                    <fullName>1008261</fullName>
                </value>
                <value>
                    <fullName>9008101</fullName>
                </value>
                <value>
                    <fullName>3008101</fullName>
                </value>
                <value>
                    <fullName>1008271</fullName>
                    <isActive>false</isActive>
                    <label>1008271</label>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>Data de Término</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <label>Data de Início</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <label>Ativo</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                    <label>Inativo</label>
                </value>
                <value>
                    <fullName>Pendente</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

pkg/objects/Project__c.object
<CustomObject>
    <fields>
        <fullName>CostCenter__c</fullName>
        <description>Type of Cost Center for the Project.</description>
        <inlineHelpText>Type of Cost Center for the Project.</inlineHelpText>
        <label>Cost center</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Nefeles</fullName>
                </value>
                <value>
                    <fullName>Customer &amp; Marketing</fullName>
                </value>
                <value>
                    <fullName>Operate</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>EndDateReal__c</fullName>
        <description>Effective end date of the project.</description>
        <inlineHelpText>Effective end date of the project.</inlineHelpText>
        <label>End date (Real)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <description>Expected date for the end of the development of the Project.</description>
        <inlineHelpText>Expected date for the end of the development of the Project.</inlineHelpText>
        <label>End date (Expected)</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Engagement__c</fullName>
        <description>Code used in Billing defines the cost/investment of a project.</description>
        <externalId>true</externalId>
        <inlineHelpText>Code used in Billing defines the cost/investment of a project.</inlineHelpText>
        <label>Engagement</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ResponsibleFunctional__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The Functional Leader responsible for the Project.</description>
        <inlineHelpText>The Functional Leader responsible for the Project.</inlineHelpText>
        <label>Responsible Functional</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects (Funcional Responsável)</relationshipLabel>
        <relationshipName>Projetos3</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleManager__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Project Manager Code.</description>
        <inlineHelpText>Project Manager Code.</inlineHelpText>
        <label>Responsible Manager</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects (Responsible Manager)</relationshipLabel>
        <relationshipName>Projects</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ResponsibleTechnician__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Technical Leader responsible for the Project.</description>
        <inlineHelpText>Technical Leader responsible for the Project.</inlineHelpText>
        <label>Responsible Technician</label>
        <referenceTo>Employee__c</referenceTo>
        <relationshipLabel>Projects (Técnico Responsável)</relationshipLabel>
        <relationshipName>Projetos2</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <description>Date when the development of the Project started.</description>
        <inlineHelpText>Date when the development of the Project started.</inlineHelpText>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>TypeContract__c</fullName>
        <description>Determines which type of Project Contract.</description>
        <inlineHelpText>Determines which type of Project Contract.</inlineHelpText>
        <label>Type of contract</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Time Material</fullName>
                </value>
                <value>
                    <fullName>Closed Scope</fullName>
                </value>
                <value>
                    <fullName>Squad</fullName>
                </value>
                <value>
                    <fullName>Delivery Pipeline</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/DeleteDailyAllocationTest.cls
@istest public class DeleteDailyAllocationTest {
    @istest public static void DeleteDailyAllocation(){
        List<DailyAllocation__c> listDays;
        Integer workingDays;
        
        Employee__c employee = new Employee__c();
        employee.Name = 'Hugo da Costa';
        Insert employee;
        
        Account account = new Account();
        account.Name = 'Paulo Machado';
        insert account;
        
        Project__c project = new Project__c();
        project.Name = 'Project Hello New';
        project.Engagement__c = '123456';
        project.ResponsibleManager__c = employee.Id;
        project.ResponsibleTechnician__c = employee.Id;
        project.ResponsibleFunctional__c = employee.Id;
        project.StartDate__c = System.Date.today();
        project.EndDate__c = System.Date.today()+7;
        project.EndDateReal__c = System.Date.today()+7;
        project.TypeContract__c = 'Time Material';
        project.CostCenter__c= 'Nefeles';
        project.Status__c = 'In progress';
		insert project;
        
        Alocation__c allocation = new Alocation__c();
        allocation.Employee__c = employee.Id;
        allocation.ProjectName__c = project.Id;
        allocation.Account__c = account.id;
        allocation.StartDate__c = date.today()+5;
        allocation.EndDate__c = date.today()+74;//It will take exactly 10 weeks
        allocation.StatusAllocation__c = 'Available';
        allocation.Workload__c = 'Part-Time';
        allocation.Category__c = 'Project';
        allocation.BillingCategory__c = 'Billable';
        allocation.StatusAfterAllocation__c = 'Reserved';
        insert allocation;
        
        /* To avoid duplication with the process builder as this test calls the invoked method directly. 
		It also doesn't matter if the process builder is inactive when moving to production. */
        delete [select id from DailyAllocation__c where Allocation__c = :allocation.id];
        
        //Call the invoked method
        CreateDailyAllocation.CreateDailyAllocation(new List<Alocation__c>{allocation});
        
        //testing if everything is ok so far.
        listDays = [select id, Date__c from DailyAllocation__c where date__c >= :allocation.StartDate__c and date__c <= :allocation.EndDate__c and Allocation__c = :allocation.id order by date__c ASC];
        workingDays = 50 - [SELECT Id FROM Holiday where ActivityDate >= :allocation.StartDate__c and ActivityDate <= :allocation.EndDate__c].size();
        system.assertEquals(workingDays, listDays.size(), 'It looks like the CreateDailyAllocation method is not working as expected');//10 weeks have 50 working days apart from Saturday and Sunday
        
        allocation.StartDate__c = date.today()+16;
        allocation.EndDate__c = date.today()+92;//It will be exactly 11 weeks
        
        test.startTest();
        DeleteDailyAllocation.DeleteDailyAllocation(new List<Alocation__c>{allocation});
        test.stopTest();
        
        listDays = [select id, date__c from DailyAllocation__c where date__c >= :allocation.StartDate__c and date__c <= :allocation.EndDate__c and Allocation__c = :allocation.id order by date__c ASC];
        system.assertEquals(0, listDays.size());//0 because the method will delete everything.
    }
    
}